# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brightness.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1780, 908)
        self.brightnessSlider = QtWidgets.QSlider(Dialog)
        self.brightnessSlider.setGeometry(QtCore.QRect(50, 390, 369, 31))
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setProperty("value", 50)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.brightnessSlider.setTickInterval(1)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.takePhoto = QtWidgets.QPushButton(Dialog)
        self.takePhoto.setGeometry(QtCore.QRect(50, 100, 99, 30))
        self.takePhoto.setObjectName("takePhoto")
        self.startRecord = QtWidgets.QPushButton(Dialog)
        self.startRecord.setGeometry(QtCore.QRect(50, 140, 99, 30))
        self.startRecord.setObjectName("startRecord")
        self.stopRecord = QtWidgets.QPushButton(Dialog)
        self.stopRecord.setGeometry(QtCore.QRect(50, 180, 99, 30))
        self.stopRecord.setObjectName("stopRecord")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 340, 188, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.brightnessDial = QtWidgets.QDial(Dialog)
        self.brightnessDial.setGeometry(QtCore.QRect(50, 440, 100, 100))
        self.brightnessDial.setMaximum(100)
        self.brightnessDial.setProperty("value", 50)
        self.brightnessDial.setNotchesVisible(True)
        self.brightnessDial.setObjectName("brightnessDial")
        self.Preview = QtWidgets.QLabel(Dialog)
        self.Preview.setGeometry(QtCore.QRect(50, 240, 58, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Preview.setFont(font)
        self.Preview.setObjectName("Preview")
        self.preview = QtWidgets.QCheckBox(Dialog)
        self.preview.setGeometry(QtCore.QRect(130, 240, 101, 27))
        self.preview.setChecked(True)
        self.preview.setObjectName("preview")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 670, 68, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(570, 90, 81, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(580, 450, 68, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(580, 290, 81, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.contrastSpin = QtWidgets.QSpinBox(Dialog)
        self.contrastSpin.setGeometry(QtCore.QRect(60, 710, 50, 32))
        self.contrastSpin.setMinimum(-100)
        self.contrastSpin.setMaximum(100)
        self.contrastSpin.setObjectName("contrastSpin")
        self.contrastSlider = QtWidgets.QSlider(Dialog)
        self.contrastSlider.setGeometry(QtCore.QRect(50, 760, 160, 26))
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.sharpnessSpin = QtWidgets.QSpinBox(Dialog)
        self.sharpnessSpin.setGeometry(QtCore.QRect(570, 130, 50, 32))
        self.sharpnessSpin.setMinimum(-100)
        self.sharpnessSpin.setMaximum(100)
        self.sharpnessSpin.setObjectName("sharpnessSpin")
        self.sharpnessSlider = QtWidgets.QSlider(Dialog)
        self.sharpnessSlider.setGeometry(QtCore.QRect(570, 190, 160, 26))
        self.sharpnessSlider.setMinimum(-100)
        self.sharpnessSlider.setMaximum(100)
        self.sharpnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpnessSlider.setObjectName("sharpnessSlider")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(580, 330, 50, 32))
        self.spinBox.setMinimum(-100)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName("spinBox")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(580, 390, 160, 26))
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.rotateImage = QtWidgets.QPushButton(Dialog)
        self.rotateImage.setGeometry(QtCore.QRect(580, 480, 99, 30))
        self.rotateImage.setObjectName("rotateImage")
        self.sharpnessDial = QtWidgets.QDial(Dialog)
        self.sharpnessDial.setGeometry(QtCore.QRect(660, 120, 50, 64))
        self.sharpnessDial.setMinimum(-100)
        self.sharpnessDial.setMaximum(100)
        self.sharpnessDial.setObjectName("sharpnessDial")
        self.saturationDial = QtWidgets.QDial(Dialog)
        self.saturationDial.setGeometry(QtCore.QRect(680, 320, 50, 64))
        self.saturationDial.setMinimum(-100)
        self.saturationDial.setMaximum(100)
        self.saturationDial.setObjectName("saturationDial")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(250, 520, 341, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.imageEffect = QtWidgets.QComboBox(self.formLayoutWidget)
        self.imageEffect.setObjectName("imageEffect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.imageEffect)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.awbMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.awbMode.setObjectName("awbMode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.awbMode)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.drcStrength = QtWidgets.QComboBox(self.formLayoutWidget)
        self.drcStrength.setObjectName("drcStrength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.drcStrength)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.exposureMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.exposureMode.setObjectName("exposureMode")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.exposureMode)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.flashMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.flashMode.setObjectName("flashMode")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.flashMode)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.meterMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.meterMode.setObjectName("meterMode")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.meterMode)
        self.brightnessSpin = QtWidgets.QSpinBox(Dialog)
        self.brightnessSpin.setGeometry(QtCore.QRect(30, 600, 183, 32))
        self.brightnessSpin.setMaximum(100)
        self.brightnessSpin.setProperty("value", 50)
        self.brightnessSpin.setObjectName("brightnessSpin")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(790, 70, 631, 151))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.sharpness1 = CompositeSlider(self.formLayoutWidget_2)
        self.sharpness1.setObjectName("sharpness1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sharpness1)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.contrast1 = CompositeSlider(self.formLayoutWidget_2)
        self.contrast1.setObjectName("contrast1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.contrast1)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.saturation1 = CompositeSlider(self.formLayoutWidget_2)
        self.saturation1.setObjectName("saturation1")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.saturation1)
        self.Preview.setBuddy(self.Preview)

        self.retranslateUi(Dialog)
        self.takePhoto.clicked.connect(Dialog.takePhoto)
        self.startRecord.clicked.connect(Dialog.startRecording)
        self.stopRecord.clicked.connect(Dialog.stopRecording)
        self.brightnessSlider.valueChanged['int'].connect(Dialog.changeBrightness)
        self.brightnessDial.sliderMoved['int'].connect(Dialog.changeBrightness)
        self.brightnessSpin.valueChanged['int'].connect(Dialog.changeBrightness)
        self.preview.clicked['bool'].connect(Dialog.showPreview)
        self.contrastSpin.valueChanged['int'].connect(Dialog.changeContrast)
        self.contrastSlider.sliderMoved['int'].connect(Dialog.changeContrast)
        self.sharpnessSpin.valueChanged['int'].connect(Dialog.changeSharpness)
        self.sharpnessSlider.sliderMoved['int'].connect(Dialog.changeSharpness)
        self.spinBox.valueChanged['int'].connect(Dialog.changeSaturation)
        self.horizontalSlider.sliderMoved['int'].connect(Dialog.changeSaturation)
        self.sharpnessDial.sliderMoved['int'].connect(Dialog.changeSharpness)
        self.saturationDial.sliderMoved['int'].connect(Dialog.changeSaturation)
        self.imageEffect.currentIndexChanged['QString'].connect(Dialog.setImageEffect)
        self.awbMode.currentIndexChanged['QString'].connect(Dialog.setAwbMode)
        self.drcStrength.currentIndexChanged['QString'].connect(Dialog.setDrcStrength)
        self.exposureMode.currentIndexChanged['QString'].connect(Dialog.setExposureMode)
        self.flashMode.currentIndexChanged['QString'].connect(Dialog.setFlashMode)
        self.meterMode.currentIndexChanged['QString'].connect(Dialog.setMeterMode)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.takePhoto.setText(_translate("Dialog", "Take Photo"))
        self.startRecord.setText(_translate("Dialog", "Start Rec"))
        self.stopRecord.setText(_translate("Dialog", "Stop Rec"))
        self.label.setText(_translate("Dialog", "Adjust Camera Brightness"))
        self.Preview.setText(_translate("Dialog", "Preview"))
        self.preview.setText(_translate("Dialog", "CheckBox"))
        self.label_2.setText(_translate("Dialog", "Contrast"))
        self.label_3.setText(_translate("Dialog", "Sharpness"))
        self.label_4.setText(_translate("Dialog", "Rotation"))
        self.label_5.setText(_translate("Dialog", "Saturation"))
        self.rotateImage.setText(_translate("Dialog", "PushButton"))
        self.label_6.setText(_translate("Dialog", "Image Effects"))
        self.label_7.setText(_translate("Dialog", "AWB Modes"))
        self.label_8.setText(_translate("Dialog", "DRC Strength"))
        self.label_9.setText(_translate("Dialog", "Exposure Mode"))
        self.label_10.setText(_translate("Dialog", "Flash Mode"))
        self.label_11.setText(_translate("Dialog", "Meter Mode"))
        self.label_12.setText(_translate("Dialog", "Sharpness"))
        self.label_13.setText(_translate("Dialog", "Contrast"))
        self.label_14.setText(_translate("Dialog", "Saturation"))

from mysliders import CompositeSlider
