# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brightness.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1780, 907)
        self.takePhoto = QtWidgets.QPushButton(Dialog)
        self.takePhoto.setGeometry(QtCore.QRect(50, 100, 99, 30))
        self.takePhoto.setObjectName("takePhoto")
        self.startRecord = QtWidgets.QPushButton(Dialog)
        self.startRecord.setGeometry(QtCore.QRect(50, 140, 99, 30))
        self.startRecord.setObjectName("startRecord")
        self.stopRecord = QtWidgets.QPushButton(Dialog)
        self.stopRecord.setGeometry(QtCore.QRect(50, 180, 99, 30))
        self.stopRecord.setObjectName("stopRecord")
        self.Preview = QtWidgets.QLabel(Dialog)
        self.Preview.setGeometry(QtCore.QRect(50, 240, 58, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Preview.setFont(font)
        self.Preview.setObjectName("Preview")
        self.preview = QtWidgets.QCheckBox(Dialog)
        self.preview.setGeometry(QtCore.QRect(130, 240, 101, 27))
        self.preview.setChecked(True)
        self.preview.setObjectName("preview")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 68, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.rotateImage = QtWidgets.QPushButton(Dialog)
        self.rotateImage.setGeometry(QtCore.QRect(50, 340, 99, 30))
        self.rotateImage.setObjectName("rotateImage")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 420, 341, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.imageEffect = QtWidgets.QComboBox(self.formLayoutWidget)
        self.imageEffect.setObjectName("imageEffect")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.imageEffect)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.awbMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.awbMode.setObjectName("awbMode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.awbMode)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.drcStrength = QtWidgets.QComboBox(self.formLayoutWidget)
        self.drcStrength.setObjectName("drcStrength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.drcStrength)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.exposureMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.exposureMode.setObjectName("exposureMode")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.exposureMode)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.flashMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.flashMode.setObjectName("flashMode")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.flashMode)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.meterMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.meterMode.setObjectName("meterMode")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.meterMode)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(400, 80, 731, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 3, 0, 3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.sharpness = CompositeSlider(self.formLayoutWidget_2)
        self.sharpness.setObjectName("sharpness")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sharpness)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.contrast = CompositeSlider(self.formLayoutWidget_2)
        self.contrast.setObjectName("contrast")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.contrast)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.brightness = CompositeSlider(self.formLayoutWidget_2)
        self.brightness.setObjectName("brightness")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.brightness)
        self.saturation = CompositeSlider(self.formLayoutWidget_2)
        self.saturation.setObjectName("saturation")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.saturation)
        self.formLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(410, 280, 721, 171))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.color_effectsV = CompositeSlider(self.formLayoutWidget_3)
        self.color_effectsV.setObjectName("color_effectsV")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.color_effectsV)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label)
        self.color_effectsU = CompositeSlider(self.formLayoutWidget_3)
        self.color_effectsU.setObjectName("color_effectsU")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.color_effectsU)
        self.colorEffectsCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.colorEffectsCheckBox.setObjectName("colorEffectsCheckBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.colorEffectsCheckBox)
        self.Preview.setBuddy(self.Preview)

        self.retranslateUi(Dialog)
        self.takePhoto.clicked.connect(Dialog.takePhoto)
        self.startRecord.clicked.connect(Dialog.startRecording)
        self.stopRecord.clicked.connect(Dialog.stopRecording)
        self.preview.clicked['bool'].connect(Dialog.showPreview)
        self.imageEffect.currentIndexChanged['QString'].connect(Dialog.setImageEffect)
        self.awbMode.currentIndexChanged['QString'].connect(Dialog.setAwbMode)
        self.drcStrength.currentIndexChanged['QString'].connect(Dialog.setDrcStrength)
        self.exposureMode.currentIndexChanged['QString'].connect(Dialog.setExposureMode)
        self.flashMode.currentIndexChanged['QString'].connect(Dialog.setFlashMode)
        self.meterMode.currentIndexChanged['QString'].connect(Dialog.setMeterMode)
        self.sharpness.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        self.contrast.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        self.saturation.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        self.brightness.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        self.color_effectsU.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        self.color_effectsV.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        self.saturation.lnValueChanged['int'].connect(Dialog.changeCameraValue)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.takePhoto.setText(_translate("Dialog", "Take Photo"))
        self.startRecord.setText(_translate("Dialog", "Start Rec"))
        self.stopRecord.setText(_translate("Dialog", "Stop Rec"))
        self.Preview.setText(_translate("Dialog", "Preview"))
        self.preview.setText(_translate("Dialog", "CheckBox"))
        self.label_4.setText(_translate("Dialog", "Rotation"))
        self.rotateImage.setText(_translate("Dialog", "PushButton"))
        self.label_6.setText(_translate("Dialog", "Image Effects"))
        self.label_7.setText(_translate("Dialog", "AWB Modes"))
        self.label_8.setText(_translate("Dialog", "DRC Strength"))
        self.label_9.setText(_translate("Dialog", "Exposure Mode"))
        self.label_10.setText(_translate("Dialog", "Flash Mode"))
        self.label_11.setText(_translate("Dialog", "Meter Mode"))
        self.label_12.setText(_translate("Dialog", "Sharpness"))
        self.label_13.setText(_translate("Dialog", "Contrast"))
        self.label_14.setText(_translate("Dialog", "Saturation"))
        self.label_15.setText(_translate("Dialog", "Brightness"))
        self.label_2.setText(_translate("Dialog", "U"))
        self.label_3.setText(_translate("Dialog", "V"))
        self.label.setText(_translate("Dialog", "Colour effects"))
        self.colorEffectsCheckBox.setText(_translate("Dialog", "CheckBox"))

from mysliders import CompositeSlider
